FreeBSD_12.1_build_fix_and_config_updates
madf/stg pull request #3
Opened 2021-02-02 16:11 UTC by bobr-kun

Added fix to prevent build crash under FreeBSD 12.1. Tested on clean FreeBSD 12.1 releases:
    FreeBSD 12.1-RELEASE FreeBSD 12.1-RELEASE
    FreeBSD 12.1-RELEASE-p13 FreeBSD 12.1-RELEASE-p13 GENERIC  amd64
    
Added 'port' option to configs

2021-02-03 16:36 UTC, madf requested changes

2021-02-03 16:36 UTC, madf commented on projects/sgconv/sgconv.conf
> +    # Default: 0
Default port shouldn't be zero.

2021-02-03 16:36 UTC, madf commented on projects/stargazer/inst/freebsd/etc/stargazer/conf-available.d/store_mysql.conf
> +    Port = 0
Please comment-out this line, the parameter is optional. Besides, 0 is a wrong value.

2021-02-03 16:36 UTC, madf commented on stglibs/pinger.lib/include/stg/pinger.h
> +#include <sys/types.h>
I don't think this fix applies for Darwin platform. Please limit it to FreeBSD and likely to FreeBSD5 and later only - there was no such problem on FreeBSD4 with gcc.

2021-02-04 11:01 UTC, madf requested changes

2021-02-04 11:01 UTC, madf commented on projects/sgconv/sgconv.conf
> +    # Default: 0
`Default` still says zero.

2021-02-04 11:01 UTC, madf commented on projects/stargazer/inst/freebsd/etc/stargazer/conf-available.d/store_mysql.conf
> +    Port = 3306
Please comment-out the param.

2021-02-04 11:01 UTC, madf commented on stglibs/pinger.lib/include/stg/pinger.h
> +#include <sys/types.h>
That's wrong. Stargazer has its own OS detection macros, and they are `FREE_BSD` and `FREE_BSD5`. You need the latter.

2021-04-04 11:39 UTC, madf commented
@bobr-kun I'm ready to merge your request but I see that there are more commits in your https://github.com/bobr-kun/stg/tree/FreeBSD_12.1_build_fix_and_config_updates branch. Please push them so I see that your work there is finished.

2021-06-24 09:09 UTC, bobr-kun commented
I'd better close this one and open a new one with all the last changes

2021-06-24 09:09 UTC, closed without merging